<?xml version="1.0" encoding="utf-8"?><Database Name="Tasks" Class="LinqtoSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Tasks.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="SmartManager.Properties.Settings" SettingsPropertyName="TasksConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="" Member="Week">
    <Type Name="Week">
      <Column Member="Monday" Type="System.String" CanBeNull="false" />
      <Column Member="Tuesday" Type="System.String" CanBeNull="false" />
      <Column Member="Wednesday" Type="System.String" CanBeNull="false" />
      <Column Member="Thursday" Type="System.String" CanBeNull="false" />
      <Column Member="Friday" Type="System.String" CanBeNull="false" />
      <Column Member="Saturday" Type="System.String" CanBeNull="false" />
      <Column Member="IdWeek" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Week_Tasks" Member="Tasks" ThisKey="IdWeek" OtherKey="Week" Type="Tasks" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Tasks">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Stage" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Task" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Week" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Association Name="Week_Tasks" Member="Week1" ThisKey="Week" OtherKey="IdWeek" Type="Week" IsForeignKey="true" />
    </Type>
  </Table>
</Database>